fix: handle a situation where article div doesn't have expected class
the podcast toolchain failed on 2023-10-13 because of this:

```console
DEBUG       : 13-Oct-23 16:47:17 https://www.znbc.co.zm:443 "GET /news/zicta-sec-sign-mou-to-protect-capital-markets-from-cyber-crimes/ HTTP/1.1" 200 1111
Traceback (most recent call last):
  File "/home/zednews/app/app/core/run.py", line 119, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/zednews/app/app/core/run.py", line 43, in main
    news = get_latest_news()
  File "/home/zednews/app/app/core/news/fetch.py", line 13, in get_latest_news
    news = get_news()
  File "/home/zednews/app/app/core/news/znbc.py", line 69, in get_news
    content = get_article_detail(detail_url)
  File "/home/zednews/app/app/core/news/znbc.py", line 26, in get_article_detail
    content_element = article.select_one("div.entry-content")
AttributeError: 'NoneType' object has no attribute 'select_one'
```